// Code generated by tygo. DO NOT EDIT.

//////////
// source: api.go

/**
 * HomeResponse represents the response for the /api/home endpoint
 */
export interface HomeResponse {
  homePath: string;
}

/**
 * ErrorResponse represents an error response
 */
export interface ErrorResponse {
  error: string;
  message: string;
}

